In [1]:
import numpy as np
import scipy
from scipy import linalg, matrix

In [2]:
A = np.array([[1, -1], [0, 1], [1, 0]])

A

array([[ 1, -1],
       [ 0,  1],
       [ 1,  0]])

In [3]:
np.roll(A[:,1], 1)

array([ 0, -1,  1])

In [4]:
display(A[:,1])
display(np.roll(A[:,1], 1))

array([-1,  1,  0])

array([ 0, -1,  1])

In [5]:
AtA = A.T.dot(A)

AtA

AAt = A.dot(A.T)

In [6]:
D, P = np.linalg.eig(AtA)

D, P

(array([3., 1.]), array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

In [7]:
ns = scipy.linalg.null_space(A)
ns * np.sign(ns[0,0]) 

IndexError: index 0 is out of bounds for axis 1 with size 0

In [8]:
D, P = np.linalg.eig(AAt)

D, P

(array([ 3.00000000e+00, -2.91433544e-16,  1.00000000e+00]),
 array([[-8.16496581e-01,  5.77350269e-01, -1.57009246e-16],
        [ 4.08248290e-01,  5.77350269e-01,  7.07106781e-01],
        [-4.08248290e-01, -5.77350269e-01,  7.07106781e-01]]))

In [9]:
np.linalg.eig(np.array([[2, 1], [0, 2]]))

(array([2., 2.]), array([[ 1.0000000e+00, -1.0000000e+00],
        [ 0.0000000e+00,  4.4408921e-16]]))

In [12]:
U, S, Vt = np.linalg.svd(A)

display(U, S, Vt)

display(A)

array([[-8.16496581e-01,  1.85577521e-16, -5.77350269e-01],
       [ 4.08248290e-01, -7.07106781e-01, -5.77350269e-01],
       [-4.08248290e-01, -7.07106781e-01,  5.77350269e-01]])

array([1.73205081, 1.        ])

array([[-0.70710678,  0.70710678],
       [-0.70710678, -0.70710678]])

array([[ 1, -1],
       [ 0,  1],
       [ 1,  0]])

In [9]:
A = np.array([[1, 1, 0], [0, 1, 1]])

A

array([[1, 1, 0],
       [0, 1, 1]])

In [10]:
A.dot(A.T)

array([[2, 1],
       [1, 2]])

In [11]:
U, S, Vt = np.linalg.svd(A)

display(U, S, Vt)

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

array([1.73205081, 1.        ])

array([[-4.08248290e-01, -8.16496581e-01, -4.08248290e-01],
       [-7.07106781e-01,  2.78976253e-16,  7.07106781e-01],
       [ 5.77350269e-01, -5.77350269e-01,  5.77350269e-01]])

In [12]:
u1 = np.array([0.70710678, 0.70710678])
u2 = np.array([-0.70710678,  0.70710678])

v1 = A.T.dot(u1) / np.sqrt(3)
v2 = A.T.dot(u2)

display(v1, v2)

array([0.40824829, 0.81649658, 0.40824829])

array([-0.70710678,  0.        ,  0.70710678])

In [13]:
1 / np.sqrt(6)

0.4082482904638631

In [14]:
np.sqrt(6) / 3

0.8164965809277259

In [15]:
1 / np.sqrt(3)

0.5773502691896258

In [16]:
A = np.array([[1, -1], [0, 1], [1, 0]])

v1 = np.array([1 / np.sqrt(2), -1 /np.sqrt(2)])
v2 = np.array([1 / np.sqrt(2), 1 /np.sqrt(2)])

In [22]:
A.dot(v1) / np.sqrt(3)

array([ 0.81649658, -0.40824829,  0.40824829])

In [20]:
A.dot(v2)

array([0.        , 0.70710678, 0.70710678])

In [23]:
np.sqrt(6)/3

0.8164965809277259

In [25]:
A.T.dot(np.array([-1, -1, 1]))

array([0, 0])

In [26]:
U = np.array([[np.sqrt(6)/3, 0, -1/np.sqrt(3)], 
              [-1/np.sqrt(6), 1/np.sqrt(2), -1/np.sqrt(3)], 
              [1/np.sqrt(6), 1/np.sqrt(2), 1/np.sqrt(3)]])

In [27]:
Sigma = np.array([[np.sqrt(3), 0], [0, 1], [0, 0]])

In [29]:
Vt = np.array([[1/ np.sqrt(2), -1 / np.sqrt(2)], [1 / np.sqrt(2), 1/np.sqrt(2)]])

In [30]:
U.dot(Sigma).dot(Vt)

array([[ 1.00000000e+00, -1.00000000e+00],
       [-8.86511593e-17,  1.00000000e+00],
       [ 1.00000000e+00, -8.86511593e-17]])